### ISSUE TITLE
Add links back to data explorer (for Atlas)

### ISSUE THREAD

**Issue by skandragon** [spinnaker/deck-kayenta#306]
For deep diving, we need a way to generate links back into Atlas (and probably other data explores) from the UI.

The legacy system at Netflix did this, and it's been noticed that we don't have it in Kayenta yet.

**Comment by skandragon** [comment]
1.  Look up the metric by name in the config file, and if it's `query.type != 'atlas'`, do nothing for now.
2.  In the data blob, find the proper scope, and get the step size and start time.
3.  Count the number of data points, to calculate the end time:  `endTime = startTime + nPoints * stepSize`
4.  construct the query URL through the attributes block for the base URL, the query, etc.
5.  Present the two links.

**Comment by erikmunson** [comment]
#308
