### ISSUE TITLE
Add a way to clone a metric in the UI

### ISSUE THREAD

**Issue by skandragon** [spinnaker/deck-kayenta#338]
Often, people want to start with a base metric and just copy it to another, tweak it, and save it.

**Comment by skandragon** [comment]
Only within a config, not across them IMHO.  Keep it simple.

We've also gotten some feedback that the icons are not always useful; perhaps they just need tooltips.  That said, insert a "copy" icon than when clicked presents a metric modal with all fields copied other than the name.  I'd probably just clear the name, forcing them to enter a new one.

**Comment by danielpeach** [comment]
We could just use the words "Edit", "Move Group", "Copy", and "Delete" instead of the icons.

**Comment by duftler** [comment]
I like the idea of just using the words.
